Mint Sign Up Page
Godswilly/HTML-Forms pull request #1
Opened 2020-05-08 19:39 UTC by Godswilly

This is an HTML document that is similar to the mints.com signup page. 
Created with HTML and CSS.

We created the following in the project:
-Navigation bar
-Sign up form
-Sign-in button
-Footer

2020-05-09 20:00 UTC, lucasmazo32 requested changes
# Changes required :wrench:

Hello Team!

The project looks good and is close to the original one. You should make changes, but they are simple.

Another thing, I know how frustrating it is when you start to change the CSS file to fulfill the requirements of the stickler, but please use descriptive commits, and if possible, make the changes in the CSS files in less commits. Remember that undescriptive commits make your project look unprofessional.

### Happy coding! :computer:

## Lucas Mazo

2020-05-09 20:00 UTC, lucasmazo32 commented on index.html
> +                                <input class = "input-info" type="text" id="email" name="email" required><br><br><br>
Please check the type that you are using for this input field.

2020-05-09 20:00 UTC, lucasmazo32 commented on index.html
> +                  <a href="#"><img src="https://i.ibb.co/MRgngMk/turbotax-logo.png" alt="turbotax-logo"></a>
Do not use screenshots for this icons. Use the icon alone and text (or image for the text as they use it on the intuit site).

2020-05-09 20:00 UTC, lucasmazo32 commented on Files/style.css
> +#already {
Do not use IDs when not necessary. In this page you should only use ID for the input fields, otherwise you should only use classes.

2020-05-09 20:15 UTC, Godswilly commented
Thank you very much sir. We really appreciate your efforts towards our
progress. We're getting better and better every day. Changes noted. You
will see a better version of us sooner than later.

On Sat, May 9, 2020, 9:00 PM Lucas Mazo <notifications@github.com> wrote:

> *@lucasmazo32* requested changes on this pull request.
> Changes required 🔧
>
> Hello Team!
>
> The project looks good and is close to the original one. You should make
> changes, but they are simple.
>
> Another thing, I know how frustrating it is when you start to change the
> CSS file to fulfill the requirements of the stickler, but please use
> descriptive commits, and if possible, make the changes in the CSS files in
> less commits. Remember that undescriptive commits make your project look
> unprofessional.
> Happy coding! 💻 Lucas Mazo
> ------------------------------
>
> In index.html
> <https://github.com/Godswilly/HTML-Forms/pull/1#discussion_r422538644>:
>
> > +                  <a href="#"><img src="https://i.ibb.co/MRgngMk/turbotax-logo.png" alt="turbotax-logo"></a>
>
> +                </div>
>
> +            </div>
>
> +
>
> +            <div>
>
> +                <form class="form-container">
>
> +                    <div>
>
> +                        <div class="form-action">
>
> +                            <h1>Create an Intuit account</h1>
>
> +                            <p>One account for everything Intuit, including Mint.<br>
>
> +                            <a id="learn-more" href="#">Learn more</a></p><br>
>
> +
>
> +
>
> +                            <div class="input-num">
>
> +                                <label  class = "label-info" for="email">Email address</label><br>
>
> +                                <input class = "input-info" type="text" id="email" name="email" required><br><br><br>
>
>
> Please check the type that you are using for this input field.
> ------------------------------
>
> In index.html
> <https://github.com/Godswilly/HTML-Forms/pull/1#discussion_r422538880>:
>
> > +                  <a href="#"><img src="https://i.ibb.co/Fgp8mrC/mint-logo.png" alt="mint-logo"></a>
>
> +                  <a href="#"><img src="https://i.ibb.co/kyxPGM9/quickbooks-logo.png" alt="quickbooks-logo"></a>
>
> +                  <a href="#"><img src="https://i.ibb.co/MRgngMk/turbotax-logo.png" alt="turbotax-logo"></a>
>
>
> Do not use screenshots for this icons. Use the icon alone and text (or
> image for the text as they use it on the intuit site).
> ------------------------------
>
> In Files/style.css
> <https://github.com/Godswilly/HTML-Forms/pull/1#discussion_r422539097>:
>
> > +  position: relative;
>
> +  background: #f5f5f5;
>
> +  background-color: #eceef1;
>
> +}
>
> +
>
> +nav {
>
> +  margin-top: 10px;
>
> +}
>
> +
>
> +.navigation-column {
>
> +  float: right;
>
> +  overflow: hidden;
>
> +  margin-right: 20px;
>
> +}
>
> +
>
> +#already {
>
>
> Do not use IDs when not necessary. In this page you should only use ID for
> the input fields, otherwise you should only use classes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Godswilly/HTML-Forms/pull/1#pullrequestreview-408679634>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AODC2P4UMNHRCBC6BUNDCELRQWY7PANCNFSM4M4NHFGQ>
> .
>

2020-05-11 08:40 UTC, trekab requested changes
# Changes Required:
Hi @Godswilly and @petersteph88, great job so far! :+1: Let's work on a few changes to complete this project.
## Required:
- [x] On the intuit products logo section, it appears that you used images with both the logo and text. The image should only be for the logo and the text shouldn't be an image. For example the Mint logo and text(logo on the left, text on the right). Please compare with the [original](https://accounts.intuit.com/signup.html). 
- [x] Remove the unnecessary padlock icon below the Sign In button.

## Optional:
- [ ] I have noticed the use of `<br> tags` in your form. The preferred practice is to use CSS whenever appropriate. Check out [this link](https://stackoverflow.com/questions/1726073/is-it-sometimes-bad-to-use-br) and [this link](https://html.com/tags/br/) for some additional explanation.

__Kindly work on the required changes and submit another code review request__
_Feel free to reach me on slack for any inquiries about this review_ :wink: 
__Treasure Kabareebe__

2020-05-11 12:20 UTC, santiago-rodrig commented
# Pull Request under review by @santiago-rodrig (TSE)

2020-05-11 12:58 UTC, santiago-dev96 requested changes
# Changes required :no_entry_sign:
You have some bad practices on your code, one of them is **using &lt;br&gt; for spacing elements, only use it inside of paragraphs if you feel it makes sense (and most of the time it doesn't')**. Take the time to read through the comments I left and implement the changes, then submit another CRR (Code Review Request).

You can find me in slack as **srodrig**, have a nice day :wave:!

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +}
This is unnecessary, [this](https://www.paulirish.com/2012/box-sizing-border-box-ftw/) is what you intended.
```suggestion
*,
*::before,
*::after {
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
}
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +  background-color: #eceef1;
Also unnecessary, you are repeating yourself.
```suggestion
  background-color: #eceef1;
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +  display: block;
It has a `display: block;` by default.
```suggestion
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +  justify-content: center;
This box doesn't have `display: flex;`, so this property does nothing.
```suggestion
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +}
You need to get familiar with the defaults as soon as possible.
```suggestion
#icons-container {
  height: 42px;
  text-align: center;
}
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +  box-sizing: border-box;
You already handled this at the top of the file.
```suggestion
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +}
Useless rule.
```suggestion
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +  text-align: justify-all;
That is not a valid value for this property. I guess that you wanted to use `justify` instead.
```suggestion
  text-align: justify;
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +  align-items: center;
This element doesn't have a `display: flex;`.
```suggestion
```

2020-05-11 12:58 UTC, santiago-rodrig commented on Files/style.css
> +}
This rule is not targeting anything.
```suggestion
```

2020-05-11 12:58 UTC, santiago-rodrig commented on README.md
> +https://rawcdn.githack.com/Godswilly/HTML-Forms/26d4c8775deb28f01f97beaaca9678e0940da10b/index.html
Make this a link.
```suggestion
[HTML-Forms](https://rawcdn.githack.com/Godswilly/HTML-Forms/26d4c8775deb28f01f97beaaca9678e0940da10b/index.html)
```

2020-05-11 12:58 UTC, santiago-rodrig commented on index.html
> +                <img src="https://plugin.intuitcdn.net/identity-authn-core-ui/1.6.5/images/turbo-tax-text.svg" alt="icon1" class="image-icon" id="turbo-tax-icon">
Don't use images for the text.
```suggestion
           <p>
                <img src="https://plugin.intuitcdn.net/identity-authn-core-ui/1.6.5/images/mint-favicon.svg" alt="icon1" class="image-icon">
                <span class="products-text">mint</span>
                <img src="https://plugin.intuitcdn.net/identity-authn-core-ui/1.6.5/images/quickbooks-favicon@2x.svg" alt="icon1" class="image-icon">
                <span class="products-text">Quickbooks</span>
                <img src="https://plugin.intuitcdn.net/identity-authn-core-ui/1.6.5/images/tt-favicon@2x.svg" alt="icon1" class="image-icon">
                <span class="products-text">turbotax</span>
            </p>
```

2020-05-11 18:40 UTC, lekegitrepo commented
#### Hi @Godswilly and @petersteph88 :clap: :clap:
#### Good job for implementing the required changes. This project is approved.

### Reviewed by Temitayo Adeleke

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

2020-05-11 18:41 UTC, lekegitrepo approved these changes
#### Status: Approved.

2020-05-11 19:05 UTC, merged